---
- name: Change ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: include vars
    include_vars: change_request_vars.yml
    
  - name: Modify a change request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: CHG0030004
      data:
        close_code: successful
        close_notes: Closing the ticket
        state: 3
    register: incident

  - debug: 
      var: incident.record.close_code
