---
- name: install mysql on DB servers
  hosts: db
  tasks:
    - name: Install MySQL 5.7 repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present
    - name: Install MySQL 5.7
      yum: pkg={{ item }}
      with_items:
      - mysql-community-server
      - mysql-community-client
      - MySQL-python
    - name: Start the MySQL service
      service: name=mysqld state=started enabled=true
    - name: Change mysql root password and keep track in 
      shell: |
        password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
        echo $password_match
        mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'PassW0rd'; flush privileges; "
        echo "[client]"
        user=root
        password=PassW0rd > /root/.my.cnf
      args:
        creates: /root/.my.cnf
      register: change_temp_pass
      notify: restart mysql
    - meta: flush_handlers
    - debug:
        var: change_temp_pass
  handlers:
    - name: restart mysql
      service: 
        name: mysqld 
        state: restarted
